version: "3.7"

services:
  mariadb:
    image: mariadb:10.3
    environment:
      MYSQL_ROOT_PASSWORD: R00t
      MYSQL_DATABASE: wp
  adminer:
    image: adminer
    ports:
      - 8080:8080
  wp:
    build: .
    working_dir: /usr/share/nginx/html
    volumes:
      - .:/usr/share/nginx/html
      - ./docker/config/php-fpm.conf:/usr/local/etc/php-fpm.d/www.conf
  nginx:
    image: nginx:1.25.2
    ports:
      - 80:80
    volumes:
      - .:/usr/share/nginx/html
      - ./docker/config/nginx.conf:/etc/nginx/conf.d/default.conf
